# Generated by Django 4.1.1 on 2022-10-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_useraccount_updated_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="useraccount",
            table="user_account",
        ),
    ]
